### PR TITLE
Update pathgo-edit.owl

### PR DESCRIPTION
**Pull request by kzudock**
addressed issues 61 & 62. added Gene's suggested terms to determinant & created corresponding terms under mechanism. USED PATHGO IDs 263-266!!!

### CODE REVIEW

**Comment by kzudock** [comment]
> 
> 
> addressed issues 61 & 62. added Gene's suggested terms to determinant & created corresponding terms under mechanism. USED PATHGO IDs 263-266!!!

CHANGED IDS TO 276-279 TO AVOID ID CONFLICTS

**Review by jacakrj1 — CHANGES_REQUESTED** [review]
Please remove www. from the Entity IRI in your New Entity Settings.

**Review by jproesch — APPROVED** [review]

**Review by jproesch — APPROVED** [review]

**Review by jproesch — APPROVED** [review]

**Review by jproesch — DISMISSED** [review]

**Comment by jproesch** [comment]
@rjacak I can't figure out what else needs to be approved here to allow the merge.  Can you take a look?

**Review by jacakrj1 — APPROVED** [review]
New terms look ok to me.  Somehow the ids reverted back to 262-267, hopefully this doesn't cause problems for us after the merge.

**Pull request merged**
