### PR TITLE
Update pathgo-edit.owl

### PR DESCRIPTION
**Pull request by kzudock**
following MAPK example, added terms for NF-kappaB under determinant and mechanism under signaling rather than immune (PATHGO 294-299). addresses issues 27-29. also fixed repeat in definition i saw.

### CODE REVIEW

**Comment by kzudock** [comment]
Second commit addressed issues 19-26. Used PATHGO IDs 300-313.  Issues 19, 21, 22, and 23 all added as mechanisms under disrupts host cellular signaling with corresponding gene product term added under cellular signaling disruption factor. Issues 24-26 added as mechanisms under mediates immune evasion and subversion and as corresponding gene products under immune evasion and subversion factor. Issue 20 deemed redundant to PATHGO 16 and terms suggested to be under it instead added under either signaling or immune evasion depending on primary effects (as outlined in term additions above). Term names and definitions were changed slightly to fit ontology format with largest change being changing "Binds parasite nucleic acid in host cell" to "enables pathogen nucleic acid concealment" and "pathogen nucleic acid concealment factor."

**Comment by kzudock** [comment]
Third commit: Somehow missed issue 30 ("Modulates host sigaling through TNF receptor-associated factors (TRAFs)"). Added under disrupts host cellular signaling and cellular signaling disruption factor as "modulates host TRAF signaling" and "TRAF signaling modulation factor", respectively.

**Comment by kzudock** [comment]
In total, this pull request address issues 19-33.

**Comment by genegodbold** [comment]
It's shaping up nicely! 
:-)

**Review by jproesch — CHANGES_REQUESTED** [review]
Please fix misspelling of "host" in definition for PATHGO_0000297 host NF-kappaB signaling modulation factor

**Comment by kzudock** [comment]
> 
> 
> Please fix misspelling of "host" in definition for PATHGO_0000297 host NF-kappaB signaling modulation factor

fixed!

**Review by jproesch — APPROVED** [review]

**Pull request merged**
